Token = input("Please enter the Bot account's Token: \t")
ChannelID = input("Please enter the Channel ID you wish to monitor: \t")
File = open("bot.py", 'r')
Contents = File.read()
File.close()
Contents = Contents.replace("**TOKEN**", Token)
Contents = Contents.replace("**CHANNEL_ID**", ChannelID)
File = open("bot.py", 'w')
File.write(Contents)
File.close()
